#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=24
#SBATCH --mem-per-cpu=1024
#SBATCH --time=48:00:00
#SBATCH --partition=open
#SBATCH --output=vasp.out
#SBATCH --error=vasp.err
#SBATCH --job-name=Pb
#SBATCH --constraint=icelake

chmod u+rwX .

# activate conda env
module load anaconda
conda activate vasp-job-automation
module load vasp
