#!/bin/bash
#SBATCH --job-name=Pb
#SBATCH -A dmr190011p
#SBATCH -p RM-shared
#SBATCH -N 1
#SBATCH --ntasks-per-node=48
#SBATCH -t 48:00:00
#SBATCH -o vasp.out
#SBATCH -e vasp.err

ulimit -s unlimited
export OMP_NUM_THREADS=1
echo "SLURM_NTASKS: " $SLURM_NTASKS

module purge
module load intel-oneapi
module load hdf5/1.12.0-intel20.4
module load anaconda3
conda activate dfttk
module load VASP/6.4.3-intel

python ev_curves.py

# Print out the SLURM JobID and job information for the current job
echo "Current SLURM JobID: $SLURM_JOB_ID"
sacct --job=$SLURM_JOB_ID
